const $=s=>document.querySelector(s), storage={get(k,fallback){try{return JSON.parse(localStorage.getItem('dashboard-'+k))??fallback}catch{return fallback}},set(k,v){localStorage.setItem('dashboard-'+k,JSON.stringify(v))}};
// Supabase email/password authentication. The publishable key is intended for browser use; never put a secret/service-role key here.
const SUPABASE_URL='https://qlbxmudwgyxiihcintxv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_HxAwsvXJ6KhBNfl8xxTCBw_vMQcpkQe';
const authMessage=$('#login-message'), authError=$('#login-error'), loginButton=$('#login-submit'), loginForm=$('#login-form'), recoveryForm=$('#recovery-form'), loginPassword=$('#login-password');
let supabaseClient=null;
function showAuthMessage(message,isError=false){authMessage.hidden=isError;authError.hidden=!isError;(isError?authError:authMessage).textContent=message}
function unlockDashboard(){document.body.classList.add('unlocked')}
function lockDashboard(){document.body.classList.remove('unlocked')}
let authMode='signin', recoveryPending=location.hash.includes('type=recovery');
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';$('#login-description').textContent=signup?'Erstelle ein Konto mit deiner E-Mail-Adresse und einem Passwort.':'Melde dich mit E-Mail und Passwort an.';loginButton.textContent=signup?'Konto erstellen':'Anmelden';$('#auth-mode-toggle').textContent=signup?'Zur Anmeldung':'Neues Konto erstellen';$('#forgot-password').hidden=signup;loginPassword.autocomplete=signup?'new-password':'current-password';loginPassword.minLength=signup?8:0;showAuthMessage('')}
function showRecoveryForm(){recoveryPending=true;loginForm.hidden=true;recoveryForm.hidden=false;lockDashboard()}
if(window.supabase?.createClient){supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);if(recoveryPending)showRecoveryForm();supabaseClient.auth.getSession().then(({data})=>{if(data.session&&!recoveryPending)unlockDashboard()});supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){showRecoveryForm();return}if(session&&!recoveryPending)unlockDashboard();else lockDashboard()})}else{showAuthMessage('Die Anmeldung konnte nicht geladen werden. Prüfe deine Internetverbindung und lade die Seite neu.',true)}
$('#auth-mode-toggle').addEventListener('click',()=>setAuthMode(authMode==='signin'?'signup':'signin'));
loginForm.addEventListener('submit',async e=>{e.preventDefault();if(!supabaseClient)return;const email=$('#login-email').value.trim(),password=loginPassword.value;loginButton.disabled=true;showAuthMessage(authMode==='signup'?'Konto wird erstellt …':'Anmeldung läuft …');try{if(authMode==='signup'){const{data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+window.location.pathname}});if(error)throw error;if(data.session){showAuthMessage('Konto erstellt. Du bist angemeldet.')}else{showAuthMessage('Konto angelegt. Bestätige deine E-Mail über den Link im Postfach; danach kannst du dich mit deinem Passwort anmelden.')}}else{const{error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error}}catch(error){showAuthMessage(error.message||'Die Anmeldung ist fehlgeschlagen.',true)}finally{loginButton.disabled=false}});
$('#forgot-password').addEventListener('click',async()=>{if(!supabaseClient)return;const email=$('#login-email').value.trim();if(!email){showAuthMessage('Gib zuerst deine E-Mail-Adresse ein.',true);return}try{const{error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+window.location.pathname});if(error)throw error;showAuthMessage('Falls ein Konto für diese Adresse besteht, wurde ein Link zum Zurücksetzen des Passworts gesendet.')}catch(error){showAuthMessage(error.message||'Der Link konnte nicht gesendet werden.',true)}});
recoveryForm.addEventListener('submit',async e=>{e.preventDefault();if(!supabaseClient)return;const button=$('#recovery-submit'),password=$('#new-password').value,errorNode=$('#recovery-error');button.disabled=true;errorNode.hidden=true;try{const{error}=await supabaseClient.auth.updateUser({password});if(error)throw error;recoveryPending=false;history.replaceState(null,'',window.location.pathname);recoveryForm.hidden=true;loginForm.hidden=false;loginPassword.value='';setAuthMode('signin');unlockDashboard()}catch(error){errorNode.textContent=error.message||'Das Passwort konnte nicht gespeichert werden.';errorNode.hidden=false}finally{button.disabled=false}});
$('#logout-button').addEventListener('click',async()=>{if(supabaseClient)await supabaseClient.auth.signOut();lockDashboard()});
const weekdays=['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'];
function updateClock(){const d=new Date();$('#clock').textContent=new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit',hour12:false}).format(d);$('#date-label').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d).toUpperCase();const h=d.getHours();$('#today-label').textContent=h<11?'Guten Morgen':h<18?'Guten Tag':'Guten Abend'}
updateClock();setInterval(updateClock,1000);
let todos=storage.get('todos',[]);function renderTodos(){const list=$('#todo-list');list.replaceChildren();todos.forEach((t,i)=>{const li=document.createElement('li');li.className='todo-item'+(t.done?' done':'');const cb=document.createElement('input');cb.type='checkbox';cb.checked=t.done;cb.setAttribute('aria-label','Aufgabe erledigt');cb.onchange=()=>{todos[i].done=cb.checked;saveTodos()};const span=document.createElement('span');span.textContent=t.text;const del=document.createElement('button');del.className='delete-todo';del.textContent='×';del.setAttribute('aria-label','Aufgabe löschen');del.onclick=()=>{todos.splice(i,1);saveTodos()};li.append(cb,span,del);list.append(li)});$('#todo-count').textContent=todos.filter(t=>!t.done).length;$('#home-todo-count').textContent=todos.filter(t=>!t.done).length;const home=$('#home-todo-list');home.replaceChildren();todos.filter(t=>!t.done).slice(0,4).forEach(t=>{const li=document.createElement('li');li.className='todo-item';const dot=document.createElement('span');dot.className='status-dot';const label=document.createElement('span');label.textContent=t.text;li.append(dot,label);home.append(li)});if(!home.children.length){const li=document.createElement('li');li.className='todo-item';li.innerHTML='<span class="muted">Alles erledigt. Zeit für etwas Neues.</span>';home.append(li)}}
function saveTodos(){storage.set('todos',todos);renderTodos()}renderTodos();$('#todo-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#todo-input'),text=input.value.trim();if(text){todos.unshift({text,done:false});input.value='';saveTodos()}});
$('#notes').value=storage.get('notes','');let noteTimer;$('#notes').addEventListener('input',()=>{$('#note-state').textContent='Speichert …';clearTimeout(noteTimer);noteTimer=setTimeout(()=>{storage.set('notes',$('#notes').value);$('#note-state').textContent='Automatisch gespeichert'},250)});
const panel=$('#calendar-settings');$('#settings-toggle').onclick=()=>{panel.hidden=!panel.hidden;$('#settings-toggle').setAttribute('aria-expanded',String(!panel.hidden))};
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.go)));function switchView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'smooth'})}const viewNames=['home','calendar','reminders','timetable','email','teams','iserv'];const initialView=location.hash.slice(1);if(viewNames.includes(initialView))switchView(initialView);
function unfold(s){return s.replace(/\\n/g,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\')}
function parseICS(raw){const lines=raw.replace(/\r?\n[ \t]/g,'').split(/\r?\n/);const out=[];let e=null;for(const line of lines){if(line==='BEGIN:VEVENT'){e={}}else if(line==='END:VEVENT'&&e){if(e.start&&e.title)out.push(e);e=null}else if(e){const p=line.indexOf(':');if(p<0)continue;const k=line.slice(0,p).split(';')[0],v=unfold(line.slice(p+1));if(k==='SUMMARY')e.title=v;if(k==='DTSTART')e.start=v;if(k==='DTEND')e.end=v}}return out.map(e=>{const all=e.start.length===8,year=+e.start.slice(0,4),month=+e.start.slice(4,6)-1,day=+e.start.slice(6,8),hour=all?0:+e.start.slice(9,11),minute=all?0:+e.start.slice(11,13);return{title:e.title,date:new Date(year,month,day,hour,minute),allDay:all}}).filter(e=>e.date>=new Date(Date.now()-86400000)).sort((a,b)=>a.date-b.date).slice(0,12)}
function renderEventList(host,items){host.replaceChildren();for(const ev of items){const row=document.createElement('div');row.className='event';const time=document.createElement('div');time.className='event-time';time.textContent=ev.allDay?'GANZTÄGIG':new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit'}).format(ev.date);const detail=document.createElement('div'),title=document.createElement('div'),date=document.createElement('div');title.className='event-title';title.textContent=ev.title;date.className='event-date';date.textContent=new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'numeric',month:'short'}).format(ev.date);detail.append(title,date);row.append(time,detail);host.append(row)}}function showEvents(items){renderEventList($('#events'),items);renderEventList($('#home-events'),items.slice(0,4));const message=items.length?`${items.length} kommende Termine`:'Keine anstehenden Termine gefunden.';$('#calendar-status').textContent=message;$('#home-calendar-status').textContent=message}
async function loadFeed(){const url=storage.get('feed','');if(!url){$('#calendar-status').textContent='Noch kein Kalender verbunden. Öffne ⚙, um deinen Feed hinzuzufügen.';return}$('#calendar-status').textContent='Kalender wird geladen …';try{const normalized=url.replace(/^webcal:/i,'https:');const res=await fetch(normalized);if(!res.ok)throw Error('http');const text=await res.text();showEvents(parseICS(text))}catch{$('#calendar-status').textContent='Der Feed ist aus dem Browser nicht erreichbar (häufig CORS). Nutze den .ics-Dateiimport oder später eine eigene sichere Schnittstelle.'}}
$('#save-feed').onclick=()=>{const value=$('#feed-url').value.trim();if(value&&!/^webcal?:\/\//i.test(value)&&!/^https?:\/\//i.test(value)){alert('Bitte einen iCloud-Link (webcal:// oder https://) einfügen.');return}storage.set('feed',value);loadFeed()};$('#feed-url').value=storage.get('feed','');$('#refresh-calendar').onclick=loadFeed;$('#ics-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{showEvents(parseICS(await file.text()))}catch{$('#calendar-status').textContent='Diese .ics-Datei konnte nicht gelesen werden.'}});$('#untis-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const lessons=parseICS(await file.text());renderEventList($('#untis-events'),lessons);$('#untis-status').textContent=lessons.length?`${lessons.length} Unterrichtstermine aus ${file.name}`:'Keine kommenden Unterrichtstermine in der Datei gefunden.';storage.set('untis-file-name',file.name)}catch{$('#untis-status').textContent='Diese .ics-Datei konnte nicht gelesen werden.'}});const iservUrl=$('#iserv-url'),iservOpen=$('#iserv-open'),homeIserv=$('#home-iserv-link');iservUrl.value=storage.get('iserv-url','');function setIservLink(value){if(/^https:\/\//i.test(value)){iservOpen.href=value;iservOpen.classList.remove('disabled-link');homeIserv.href=value}else{iservOpen.href='https://iserv.eu/';iservOpen.classList.add('disabled-link');homeIserv.href='https://iserv.eu/'}}setIservLink(iservUrl.value);$('#iserv-form').addEventListener('submit',e=>{e.preventDefault();const value=iservUrl.value.trim();if(value&&!/^https:\/\//i.test(value)){alert('Bitte eine vollständige sichere Adresse mit https:// eingeben.');return}storage.set('iserv-url',value);setIservLink(value)});loadFeed();
